# Generated by Django 5.1.6 on 2025-06-26 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCustomerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Fornecedores e Cliente',
                'db_table': 'type_customer_suppliers',
            },
        ),
        migrations.CreateModel(
            name='CustomerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome ou Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('phone1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone 1')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone 2')),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Civil')),
                ('profession', models.CharField(blank=True, max_length=30, null=True, verbose_name='Profissão')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('date_birth', models.DateTimeField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_supplier_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_supplier_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('type_customer_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_suppliers.typecustomersupplier', verbose_name='Tipo de cadastro')),
            ],
            options={
                'verbose_name': 'Fornecedores Cliente',
                'db_table': 'customer_suppliers',
            },
        ),
    ]
