# Generated by Django 5.1.6 on 2025-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome ou Razão Social'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
    ]
