# Generated by Django 5.1.6 on 2025-03-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupplier',
            options={'verbose_name': 'Fornecedores Cliente'},
        ),
        migrations.AlterModelTable(
            name='customersupplier',
            table='customer_suppliers',
        ),
    ]
