# Generated by Django 5.1.6 on 2025-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersupplier',
            name='type_customer_supplier',
        ),
        migrations.AddField(
            model_name='customersupplier',
            name='type_customer_supplier',
            field=models.ManyToManyField(to='customer_suppliers.typecustomersupplier', verbose_name='Tipo de cadastro'),
        ),
    ]
