# Generated by Django 5.1.6 on 2025-06-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0002_remove_customersupplier_type_customer_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupplier',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
    ]
