# Generated by Django 5.1.6 on 2025-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0002_alter_customersupplier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupplier',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
