# Generated by Django 5.1.6 on 2025-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0003_customersupplier_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupplier',
            name='cpf',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
