# Generated by Django 5.1.6 on 2025-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0004_alter_customersupplier_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersupplier',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='customersupplier',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customersupplier',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
