# Generated by Django 5.1.6 on 2025-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0005_rename_phone_customersupplier_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupplier',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
