# Generated by Django 5.1.6 on 2025-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0006_customersupplier_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupplier',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
