# Generated by Django 5.1.6 on 2025-03-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0008_customersupplier_rg_alter_customersupplier_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupplier',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
