# Generated by Django 5.1.6 on 2025-05-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0010_alter_customersupplier_phone1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersupplier',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customersupplier',
            name='phone2',
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='type',
            field=models.IntegerField(choices=[('CUSTOMER', 'Cliente'), ('SUPPLIER', 'Fornecedor'), ('BOTH', 'Ambos')]),
        ),
    ]
