# Generated by Django 5.1.6 on 2025-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0011_rename_phone1_customersupplier_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupplier',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
