# Generated by Django 5.1.6 on 2025-06-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0012_customersupplier_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone 1'),
        ),
    ]
