# Generated by Django 5.1.6 on 2025-06-18 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('property_registration', models.CharField(max_length=30, verbose_name='Matrícula')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'db_table': 'enterprises',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='debits.enterprise', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Quadra',
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=100, verbose_name='Lote')),
                ('square_meters', models.FloatField(verbose_name='Metros quadrados')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do lote')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('property_registration', models.CharField(max_length=30, verbose_name='Matrícula')),
                ('municipal_registration', models.CharField(max_length=30, verbose_name='Inscrição municipal')),
                ('front_footage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem frente')),
                ('bottom_footage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem fundo')),
                ('right_footage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem direita')),
                ('left_footage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem esquerda')),
                ('corner_footage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem esquina')),
                ('front_confrontation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação frente')),
                ('bottom_confrontation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação fundo')),
                ('right_confrontation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação direita')),
                ('left_confrontation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação esquerda')),
                ('is_property_deed', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='debits.block', verbose_name='Quadra')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Lote',
                'db_table': 'lots',
            },
        ),
        migrations.CreateModel(
            name='SalesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Data do contrato')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data inicial das parcelas')),
                ('number_of_installment', models.IntegerField(blank=True, null=True, verbose_name='Número de parcelas')),
                ('installment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor das parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contract_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customer_suppliers.customersupplier', verbose_name='Cliente')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contracts', to='debits.lot', verbose_name='Lote')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contract_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
        ),
    ]
