# Generated by Django 5.1.6 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
    ]
