# Generated by Django 5.1.6 on 2025-06-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='latest_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
