# Generated by Django 5.1.6 on 2025-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0002_lot_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescontract',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
