# Generated by Django 5.1.6 on 2025-08-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0002_alter_salescontract_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código ERP'),
        ),
    ]
