# Generated by Django 5.1.6 on 2025-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0002_alter_enterprise_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='bottom_confrontation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação fundo'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='bottom_footage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem fundo'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='corner_footage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem esquina'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='front_confrontation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação frente'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='front_footage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem frente'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='left_confrontation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação esquerda'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='left_footage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem esquerda'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='right_confrontation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Confrontação direita'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='right_footage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Metragem direita'),
        ),
    ]
