# Generated by Django 5.1.6 on 2025-08-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0003_enterprise_erp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='erp_code',
            new_name='code_erp',
        ),
    ]
