# Generated by Django 5.1.6 on 2025-09-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0004_rename_erp_code_enterprise_code_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescontract',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor entrada'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='number_of_installment_down_payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de parcelas da entrada'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor venda'),
        ),
    ]
