# Generated by Django 5.1.6 on 2025-06-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0004_alter_salescontract_installment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescontract',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_contracts', to='debits.lot', verbose_name='Lote'),
            preserve_default=False,
        ),
    ]
