# Generated by Django 5.1.6 on 2025-06-09 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0005_salescontract_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescontract',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contracts', to='debits.lot', verbose_name='Lote'),
        ),
    ]
