# Generated by Django 5.1.6 on 2025-09-09 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0003_alter_customersupplier_profession'),
        ('debits', '0005_salescontract_down_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescontract',
            options={'verbose_name': 'Contratos de venda'},
        ),
        migrations.AddConstraint(
            model_name='salescontract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('lot',), name='unique_active_contract_per_lot'),
        ),
        migrations.AlterModelTable(
            name='salescontract',
            table='sales_contracts',
        ),
    ]
