# Generated by Django 5.1.6 on 2025-06-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0006_alter_salescontract_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescontract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do contrato'),
        ),
    ]
