# Generated by Django 5.1.6 on 2025-09-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0006_alter_salescontract_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salescontract',
            name='unique_active_contract_per_lot',
        ),
    ]
