# Generated by Django 5.1.6 on 2025-09-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0007_remove_salescontract_unique_active_contract_per_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescontract',
            name='down_payment_installment_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor parcela da entrada'),
        ),
    ]
