# Generated by Django 5.1.6 on 2025-06-18 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_suppliers', '0002_alter_customersupplier_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_holder_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_holders', to='customer_suppliers.customersupplier', verbose_name='Cliente / Fornecedor')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_holder_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Titular conta',
                'db_table': 'account_holders',
            },
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('bank', models.CharField(max_length=50, verbose_name='Banco')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial')),
                ('agency', models.CharField(max_length=50, verbose_name='Agência')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número da conta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_accounts', to='financials.accountholder')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_account_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_account_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Contas Corrente',
                'db_table': 'checking_accounts',
            },
        ),
        migrations.CreateModel(
            name='CheckingAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checking_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='financials.checkingaccount')),
            ],
            options={
                'verbose_name': 'Saldo',
                'db_table': 'checking_account_balances',
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Despesa'), (1, 'Receita')], default=0, verbose_name='Tipo')),
                ('is_default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome da categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_category_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_category_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Financeiro Categoria',
                'db_table': 'financial_categories',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(0, 'A pagar'), (1, 'A receber')], verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da parcela')),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor entrada (se houver)')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('number_of_installments', models.IntegerField(verbose_name='número de parcela')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='financials.accountholder', verbose_name='Titular da conta')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customer_suppliers.customersupplier', verbose_name='Cliente / Fornecedor')),
                ('financial_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.financialcategory', verbose_name='Categorias')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Financeiro Conta',
                'db_table': 'financial_transactions',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransactionInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='Número parcela')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('status', models.IntegerField(choices=[(0, 'Não pago'), (1, 'Pago')], default=0)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor pago')),
                ('settlement_date', models.DateTimeField(blank=True, null=True, verbose_name='Data baixa')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_installment_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('financial_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financials.financialtransaction')),
                ('marked_down_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_installments', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_installment_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Financeiro Parcela',
                'db_table': 'financial_transaction_installments',
            },
        ),
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(0, 'Saída'), (1, 'Entrada')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_date', models.DateField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checking_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='financials.checkingaccount')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_movements_installment_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_movements_installment_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('financial_transaction_installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='financials.financialtransactioninstallment')),
            ],
            options={
                'verbose_name': 'Movimentações Financeira',
                'db_table': 'financial_movements',
            },
        ),
    ]
