# Generated by Django 5.1.6 on 2025-03-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=50)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_account_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_account_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Contas Corrente',
            },
        ),
        migrations.CreateModel(
            name='CheckingAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checking_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='financials.checkingaccount')),
            ],
            options={
                'verbose_name': 'Saldo',
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(0, 'Despesa'), (1, 'Receita')])),
                ('is_default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_category_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_category_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Financeiro Categoria',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(0, 'A pagar'), (1, 'A receber')])),
                ('description', models.CharField(max_length=255)),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_installments', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customer_suppliers.customersupplier')),
                ('financial_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.financialcategory')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Financeiro Conta',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransactionInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Não pago'), (1, 'Pago')], default=0)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_installment_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('financial_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financials.financialtransaction')),
                ('marked_down_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_installments', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_installment_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Financeiro Parcela',
            },
        ),
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(0, 'Saída'), (1, 'Entrada')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checking_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='financials.checkingaccount')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_movements_installment_user_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_movements_installment_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('financial_transaction_installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='financials.financialtransactioninstallment')),
            ],
            options={
                'verbose_name': 'Movimentações Financeira',
            },
        ),
    ]
