# Generated by Django 5.1.6 on 2025-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_remove_financialcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
    ]
