# Generated by Django 5.1.6 on 2025-06-25 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0002_lot_latest_update'),
        ('financials', '0003_financialmovement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transaction_lot', to='debits.lot', verbose_name='Lote'),
        ),
    ]
