# Generated by Django 5.1.6 on 2025-03-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_checkingaccount_account_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtransaction',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='account_holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='financials.accountholder'),
            preserve_default=False,
        ),
    ]
