# Generated by Django 5.1.6 on 2025-03-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_remove_financialtransaction_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
