# Generated by Django 5.1.6 on 2025-03-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_alter_financialtransaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtransactioninstallment',
            name='created_at',
        ),
    ]
