# Generated by Django 5.1.6 on 2025-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_remove_financialtransactioninstallment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransactioninstallment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
