# Generated by Django 5.1.6 on 2025-03-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0010_alter_customersupplier_phone1_and_more'),
        ('financials', '0008_alter_financialtransactioninstallment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='financials.accountholder', verbose_name='Titular da conta'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='customer_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customer_suppliers.customersupplier', verbose_name='Cliente / Fornecedor'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor entrada (se houver)'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='due_date',
            field=models.DateField(verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='financial_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.financialcategory', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='installment_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da parcela'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='number_of_installments',
            field=models.IntegerField(verbose_name='número de parcela'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='type',
            field=models.BooleanField(choices=[(0, 'A pagar'), (1, 'A receber')], verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='financialtransactioninstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='financialtransactioninstallment',
            name='due_date',
            field=models.DateField(verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='financialtransactioninstallment',
            name='installment_number',
            field=models.IntegerField(verbose_name='Número parcela'),
        ),
        migrations.AlterField(
            model_name='financialtransactioninstallment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor pago'),
        ),
        migrations.AlterField(
            model_name='financialtransactioninstallment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='financialtransactioninstallment',
            name='settlement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data baixa'),
        ),
    ]
