# Generated by Django 5.1.6 on 2025-04-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_suppliers', '0010_alter_customersupplier_phone1_and_more'),
        ('financials', '0009_financialmovement_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='customer_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_holders', to='customer_suppliers.customersupplier', verbose_name='Cliente / Fornecedor'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Número da conta'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='agency',
            field=models.CharField(max_length=50, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='bank',
            field=models.CharField(max_length=50, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
