# Generated by Django 5.1.6 on 2025-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_alter_accountholder_customer_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor entrada (se houver)'),
        ),
    ]
