# Generated by Django 5.1.6 on 2025-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_alter_financialtransaction_down_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='financialcategory',
            name='type',
            field=models.BooleanField(choices=[(0, 'Despesa'), (1, 'Receita')], verbose_name='Tipo'),
        ),
    ]
