# Generated by Django 5.1.6 on 2025-05-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_alter_financialcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcategory',
            name='type',
            field=models.IntegerField(choices=[(0, 'Despesa'), (1, 'Receita')], verbose_name='Tipo'),
        ),
    ]
